#!/usr/bin/env bun
// Rust Code Studio — prompt-time memory recall + routing nudge (UserPromptSubmit).
//
// For UserPromptSubmit the documented mechanism is the simplest one: whatever the
// hook prints to stdout on exit 0 is added to the prompt context. Two things ride it:
//
// 1) PROMPT-SCOPED RECALL — the host loads the whole memory index at session start
//    but never says which notes matter for THIS prompt. So each prompt is matched
//    against the index (title, slug, one-line hook); a note that scores a strong hit
//    is surfaced once per session as a pointer (title, kind/age, path). Cheap: one
//    ≤25 KB file read; silent when nothing matches or the note was already surfaced.
// 2) ROUTING NUDGE — once per session: prefer a studio skill over ad-hoc steps and
//    /recall the area before implementing.
//
// A third thing rides it without printing anything: a prompt that opens with a studio skill
// (`/review …`, `/rust-studio:dev-task …`) is a USER invocation, which never passes through
// the Skill tool and so never reaches the PostToolUse usage log. It is appended here
// instead, so the usage report counts both hands (usage-log.ts).
//
// What is deliberately NOT here any more: the per-prompt regex route hint that named the
// skill a prompt's SHAPE pointed at (0.44 to 0.55). Retired 2026-09-14 on an audit of 1,187
// sessions: 114 of its 123 firings (93%) were on `<task-notification>` — sub-agent
// completions that pass through this event as prompts — and the model obeyed 6 of 123
// (0 of 17 for `/review`). It had taught the model the hint is ignorable. And no
// prompt-shape router could work on the real traffic: 90% of the human prompts were
// Russian, 73% under 120 characters, none carried an `error[E…]`, a panic, a diff or a
// `-->` location. Routing lives in the skill descriptions and the routing evals; the
// usage log measures whether that is enough.
//
// Machine-generated prompts — task notifications, teammate messages, command echoes,
// bash-mode output — are ignored whole (`isMachinePrompt`), so neither the recall nor the
// nudge fires on text no human typed.
//
// Never blocks (no decision:block) and never fails the session. Codex delivers the
// same event; if its payload carries no `prompt`, only the nudge runs.

import { emitUserPromptContext, readInput, watchdog, optionBool, pluginRoot, pluginData } from "./_lib.ts";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  labelFor,
  rankEntries,
  readIndex,
  resolveStore,
  terms,
  type IndexEntry,
  type Ranked,
} from "./memory-store.ts";
import { appendUsage } from "./usage-log.ts";

/** A pointer needs a strong hit (slug/title) or three weak ones — one shared word in
 *  a hook is noise, not recall. */
export const MIN_PROMPT_SCORE = 3;
export const MAX_PROMPT_POINTERS = 3;

/** How a prompt that no human typed begins. Every entry is a shape seen in real transcripts:
 *  a sub-agent completion (`<task-notification>`, 1,096 of 1,996 main-session prompts in
 *  the audit), a teammate or agent message, the echo of a slash command or of bash mode,
 *  a host check-in, the expanded body of a skill, and the interrupt marker. A prompt that
 *  merely CONTAINS one of these later on is a human pasting something, and stays a prompt. */
export const MACHINE_PROMPT_PREFIXES: readonly string[] = [
  "<task-notification>",
  "<agent-message",
  "<teammate-message",
  "<command-name>",
  "<command-message>",
  "<local-command",
  "<bash-input>",
  "<bash-stdout>",
  "<bash-stderr>",
  "<system-reminder>",
  "Stop hook feedback:",
  "Goal check-in:",
  "Base directory for this skill:",
  "[Request interrupted",
];

/** Was this prompt generated by the host or a sub-agent rather than typed by a person? Pure. */
export function isMachinePrompt(prompt: unknown): boolean {
  if (typeof prompt !== "string") return false;
  const head = prompt.trimStart();
  return MACHINE_PROMPT_PREFIXES.some((p) => head.startsWith(p));
}

/** Pure selection: which index entries does this prompt recall, minus ones already
 *  surfaced this session. */
export function pickPromptPointers(entries: IndexEntry[], prompt: string, already: Set<string>): Ranked[] {
  const sig = terms(prompt);
  if (sig.size === 0) return [];
  return rankEntries(entries, sig, MAX_PROMPT_POINTERS + already.size)
    .filter((r) => r.score >= MIN_PROMPT_SCORE && !already.has(r.file))
    .slice(0, MAX_PROMPT_POINTERS);
}

export function renderPointers(dir: string, picks: Ranked[], labelOf: (file: string) => string): string {
  const d = dir.replace(/\\/g, "/");
  return (
    `Rust Code Studio memory — ${picks.length === 1 ? "a note matches" : `${picks.length} notes match`} this prompt ` +
    "(read before re-deriving; verify a note still holds before it steers):\n" +
    picks.map((p) => `- **${p.title}**${labelOf(p.file)}${p.hook ? ` — ${p.hook}` : ""} → \`${d}/${p.file}\``).join("\n")
  );
}

let skillNames: Set<string> | null = null;
/** The plugin's skill directory names, read once; null when the plugin root is not readable. */
function knownSkills(): Set<string> | null {
  if (skillNames) return skillNames;
  try {
    skillNames = new Set(readdirSync(join(pluginRoot(), "skills")));
  } catch {
    skillNames = null;
  }
  return skillNames;
}

/** The studio skills a prompt invokes (`/review`, `/rust-studio:review`), in order, without
 *  duplicates. A slash token that continues as a path (`/home/me`, `/src/lib.rs`) or names no
 *  shipped skill is not an invocation. Without a readable skills directory, a bare `/name` is
 *  taken on its shape alone. */
export function studioSkillsNamed(text: string): string[] {
  const skills = knownSkills();
  const out: string[] = [];
  for (const m of text.matchAll(/(^|[\s(`])\/(rust-studio:)?([a-z][a-z-]+)\b(?![\/.])/g)) {
    if ((m[2] || !skills || skills.has(m[3])) && !out.includes(m[3])) out.push(m[3]);
  }
  return out;
}

/** Does the prompt name a studio skill anywhere? */
export function namesStudioSkill(text: string): boolean {
  return studioSkillsNamed(text).length > 0;
}

/** The skill a prompt INVOKES: a leading `/name`, the shape the host expands as a command. A
 *  name further in ("вместо полного /dev-task", a pasted plan) is a mention, and if the model
 *  acts on it the Skill tool logs that call as its own. In the audit's transcripts 55 of 61
 *  prompts naming a skill named it mid-sentence. */
export function userInvokedSkill(text: string): string | null {
  const m = /^\s*\/(rust-studio:)?([a-z][a-z-]+)\b(?![\/.])/.exec(text);
  if (!m) return null;
  const skills = knownSkills();
  return m[1] || !skills || skills.has(m[2]) ? m[2] : null;
}

function markerDir(name: string): string {
  return join(pluginData(), name);
}

/** A per-session set persisted as a JSON array in `<tmpdir>/<name>/<sid>`; unreadable or
 *  malformed → empty. One scheme for recall pointers and the routing nudge. */
export function readMarkerSet(name: string, sid: string): Set<string> {
  try {
    const parsed = JSON.parse(readFileSync(join(markerDir(name), sid), "utf8"));
    return new Set(Array.isArray(parsed) ? parsed.filter((x): x is string => typeof x === "string") : []);
  } catch {
    return new Set();
  }
}
export function writeMarkerSet(name: string, sid: string, items: Set<string>): void {
  try {
    mkdirSync(markerDir(name), { recursive: true });
    writeFileSync(join(markerDir(name), sid), JSON.stringify([...items]));
  } catch {
    /* non-fatal */
  }
}

/** Files already surfaced this session. */
export const readSurfaced = (sid: string): Set<string> => readMarkerSet("rust-studio-recall", sid);
export const writeSurfaced = (sid: string, files: Set<string>): void => writeMarkerSet("rust-studio-recall", sid, files);

if (import.meta.main) {
  const disarm = watchdog(6_000);
  const data = await readInput<{ session_id?: string; prompt?: string; cwd?: string }>();

  const out: string[] = [];
  // Without a session_id there is no per-session key: a shared marker would mute every
  // later id-less session and no marker would spam every prompt — stay quiet.
  const sid = data.session_id ? String(data.session_id).replace(/[^A-Za-z0-9]/g, "_") : "";
  const prompt = typeof data.prompt === "string" ? data.prompt : "";
  const human = prompt.trim().length > 0 && !isMachinePrompt(prompt);

  // 0) usage telemetry — a user-typed `/skill` is an invocation the Skill tool never sees.
  const invoked = human ? userInvokedSkill(prompt) : null;
  if (invoked) appendUsage({ session_id: data.session_id, cwd: data.cwd, kind: "skill", name: invoked, invoker: "user" });

  // 1) prompt-scoped recall
  if (sid && human && optionBool("memory_recall", true)) {
    try {
      const store = resolveStore(data.cwd || process.cwd());
      const index = store.exists ? readIndex(store.dir) : null;
      if (index && index.entries.length) {
        const already = readSurfaced(sid);
        const picks = pickPromptPointers(index.entries, prompt, already);
        if (picks.length) {
          out.push(renderPointers(store.dir, picks, (f) => labelFor(store.dir, f)));
          for (const p of picks) already.add(p.file);
          writeSurfaced(sid, already);
        }
      }
    } catch {
      /* recall is best-effort */
    }
  }

  // 2) routing nudge, once per session. A machine-generated prompt does not spend it: the
  //    first HUMAN prompt of the session should be the one that carries it.
  if (sid && !isMachinePrompt(prompt) && optionBool("routing_nudge", true)) {
    try {
      const nudged = readMarkerSet("rust-studio-nudge", sid);
      if (!nudged.has("shown")) {
        writeMarkerSet("rust-studio-nudge", sid, new Set(["shown"]));
        out.push(
          "Rust Code Studio: for any non-trivial task, prefer a studio skill (`/help` " +
            "for the catalog) over ad-hoc steps, and run `/recall <area>` before " +
            "implementing in a known area so prior decisions and gotchas carry forward.",
        );
      }
    } catch {
      /* emit nothing rather than risk spamming */
    }
  }

  disarm();
  if (out.length) emitUserPromptContext(out.join("\n\n"));
  process.exit(0);
}
